import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm";
const supabase=createClient("https://otgubsvmcbaocrndngrq.supabase.co","sb_publishable__d50uWZVhfLcfzHv70ZOSA_QySE92AW",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const S={tab:'home',step:1,authMode:'login',user:null,est:null,member:null,spaces:[],screens:[],name:'Mon établissement',filter:'Toutes',questions:[['Quel groupe a interprété « Bohemian Rhapsody » ?','Musique','Queen'],['Quelle est la capitale du Portugal ?','Géographie','Lisbonne'],['Combien font 12 × 8 ?','Calcul','96'],['En quelle année débute la Révolution française ?','Histoire','1789'],['Quel joueur a remporté le plus de Ballons d’Or ?','Sport','Lionel Messi']]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function show(id){$$('.page').forEach(x=>x.classList.remove('on'));$('#'+id).classList.add('on');scrollTo(0,0)}
function msg(t,ok=false){const x=$('#authMessage');x.style.display=t?'block':'none';x.textContent=t||'';x.classList.toggle('success',ok)}
function openAuth(m){S.authMode=m;msg('');$('#authTitle').textContent=m==='signup'?'Créer votre établissement':'Connexion';$('#authIntro').textContent=m==='signup'?'Démarrez vos 14 jours d’essai gratuit.':'Accédez à l’espace de votre établissement.';$('#signupFields').style.display=m==='signup'?'block':'none';$('#trialNotice').style.display=m==='signup'?'block':'none';$('#authSubmit').textContent=m==='signup'?'Créer mon compte et démarrer l’essai':'Se connecter';$('#switchAuth').textContent=m==='signup'?'J’ai déjà un compte':'Créer un compte';$('#password').autocomplete=m==='signup'?'new-password':'current-password';show('auth')}
function active(){const e=S.est;if(!e||e.enabled===false)return false;const n=Date.now();return e.subscription_status==='trialing'?new Date(e.trial_ends_at).getTime()>n:e.subscription_status==='active'&&(!e.current_period_end||new Date(e.current_period_end).getTime()>n)}
function days(){return S.est?.trial_ends_at?Math.max(0,Math.ceil((new Date(S.est.trial_ends_at)-Date.now())/86400000)):0}
function sync(){const e=S.est;S.name=e.name;$('#venueLabel').textContent=e.name;$('#tvVenue').textContent=e.name;$('#planLabel').textContent=(e.plan_code||e.subscription_status||'essai').toUpperCase();$('#trialLabel').textContent=e.subscription_status==='trialing'?`Essai gratuit : ${days()} jour${days()>1?'s':''} restant${days()>1?'s':''}`:e.subscription_status==='active'?`Abonnement actif${e.current_period_end?' · jusqu’au '+new Date(e.current_period_end).toLocaleDateString('fr-FR'):''}`:e.subscription_status==='past_due'?'Paiement en attente':'Accès suspendu'}
async function loadAccount(){const{data:{user},error:ue}=await supabase.auth.getUser();if(ue||!user)throw new Error('Session invalide.');S.user=user;const{data:m,error:me}=await supabase.from('nightquiz_memberships').select('establishment_id,role').eq('user_id',user.id).limit(1);if(me)throw me;if(!m?.length)throw new Error('Ce compte n’est associé à aucun établissement NIGHTQUIZ.');S.member=m[0];const id=m[0].establishment_id;const[a,b,c]=await Promise.all([supabase.from('nightquiz_establishments').select('*').eq('id',id).single(),supabase.from('nightquiz_spaces').select('*').eq('establishment_id',id).order('created_at'),supabase.from('nightquiz_screens').select('*').eq('establishment_id',id).order('created_at')]);if(a.error)throw a.error;if(b.error)throw b.error;if(c.error)throw c.error;S.est=a.data;S.spaces=b.data||[];S.screens=c.data||[];sync();S.tab=active()?'home':'billing';render();show('app')}
$$('[data-auth]').forEach(b=>b.onclick=()=>openAuth(b.dataset.auth));$('#authBack').onclick=()=>show('landing');$('#switchAuth').onclick=()=>openAuth(S.authMode==='login'?'signup':'login');
$('#authForm').onsubmit=async e=>{e.preventDefault();msg('');const btn=$('#authSubmit'),email=$('#email').value.trim(),password=$('#password').value;btn.disabled=true;const txt=btn.textContent;btn.textContent='Connexion…';try{if(S.authMode==='signup'){const venue=$('#venueName').value.trim();if(!venue)throw new Error('Indiquez le nom de votre établissement.');const{data,error}=await supabase.auth.signUp({email,password,options:{data:{nightquiz_establishment_name:venue}}});if(error)throw error;if(!data.session){msg('Compte créé. Confirmez votre adresse e-mail puis revenez vous connecter.',true);return}await loadAccount()}else{const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;await loadAccount()}}catch(er){msg(er.message||'Impossible de vous connecter.')}finally{btn.disabled=false;btn.textContent=txt}};
$('#logout').onclick=async()=>{await supabase.auth.signOut();S.user=S.est=S.member=null;S.spaces=[];S.screens=[];show('landing')};
function layout(t,s,a='',b=''){return`<header class="head"><div><span class="pill">ESPACE ÉTABLISSEMENT</span><h1>${t}</h1><p class="muted">${s}</p></div>${a}</header>${b}`}
function home(){const a=active()?'<button class="btn primary" data-tab="new">＋ Nouvelle partie</button>':'<button class="btn primary" data-tab="billing">Activer l’abonnement</button>';return layout(`Bonsoir, ${S.name} 👋`,'Voici l’activité de votre établissement.',a,`<div class="grid4"><div class="stat"><small>PARTIES CE MOIS</small><b>12</b></div><div class="stat"><small>JOUEURS</small><b>428</b></div><div class="stat"><small>TAUX DE RÉPONSE</small><b>91%</b></div><div class="stat"><small>QUESTIONS</small><b>2 072</b></div></div><div class="cols"><div class="card"><small>PROCHAINE SOIRÉE</small><h3>Quiz Général · Vendredi</h3><p class="muted">Espace principal · 21:00 · 30 questions</p><div class="code"><b>4827</b><button class="btn primary" id="openTv">▶ Écran TV</button></div></div><div class="card"><small>PARTICIPATION</small><div class="bars"><i style="height:42%"></i><i style="height:58%"></i><i style="height:49%"></i><i style="height:71%"></i><i style="height:83%"></i><i style="height:100%"></i></div></div></div>`)}
function newGame(){let c=S.step===1?`<div class="field"><label>NOM</label><input value="Quiz Général — Vendredi"></div><div class="field"><label>ESPACE</label><select>${S.spaces.map(x=>`<option>${x.name}</option>`).join('')}</select></div><div class="field"><label>NOMBRE DE QUESTIONS</label><div class="choices"><button>20</button><button class="sel">30</button><button>50</button><button>100</button></div></div>`:S.step===2?`<div class="cats"><button class="on">Musique</button><button class="on">Culture générale</button><button class="on">Sport</button><button>Histoire</button><button>Logique</button><button>Sciences</button><button>Nature</button><button>Calcul</button></div>`:S.step===3?`<div class="field"><label>1ER PRIX</label><input value="50€ de consommation"></div><div class="field"><label>2E PRIX</label><input value="1 bouteille de bulles"></div><div class="field"><label>3E PRIX</label><input value="1 consommation"></div>`:`<div class="notice success">✓ Partie prête pour ${S.name}.</div>`;return layout('Nouvelle partie','Configurez votre soirée en 4 étapes.','',`<div class="steps">${['Format','Catégories','Lots','Confirmation'].map((x,i)=>`<span class="${S.step===i+1?'on':''}"><b>${i+1}</b> ${x}</span>`).join('')}</div><div class="card">${c}<div style="display:flex;justify-content:space-between;margin-top:20px"><button class="btn" id="prev">← Retour</button><button class="btn primary" id="next">${S.step===4?'Ouvrir la TV':'Continuer →'}</button></div></div>`)}
function questions(){const r=S.questions.filter(q=>S.filter==='Toutes'||q[1]===S.filter);return layout('Questions','Banque officielle + questions privées.','',`<div class="toolbar">${['Toutes','Musique','Sport','Histoire','Calcul'].map(x=>`<button class="btn ${S.filter===x?'primary':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="card"><div class="notice">Les questions privées de ${S.name} restent invisibles aux autres établissements.</div><table class="table"><tr><th>QUESTION</th><th>CATÉGORIE</th><th>RÉPONSE</th></tr>${r.map(q=>`<tr><td>${q[0]}</td><td><span class="tag">${q[1]}</span></td><td>${q[2]}</td></tr>`).join('')}</table></div>`)}
function stats(){return layout('Statistiques','Performance de vos soirées.','',`<div class="grid4"><div class="stat"><small>JOUEURS</small><b>428</b></div><div class="stat"><small>PARTIES</small><b>12</b></div><div class="stat"><small>MOYENNE</small><b>35,7</b></div><div class="stat"><small>FIDÉLITÉ</small><b>34%</b></div></div>`)}
function spaces(){const cards=S.spaces.map(sp=>{const n=S.screens.filter(x=>x.space_id===sp.id).length;return`<div class="space"><span class="dot"></span><b>${sp.name}</b><p class="muted">${n} écran${n>1?'s':''} associé${n>1?'s':''}</p><button class="btn openTv">Ouvrir la TV</button></div>`}).join('');return layout('Espaces & TV','Vos espaces et écrans réels chargés depuis Supabase.','',`<div class="notice">Ces données appartiennent uniquement à ${S.name}.</div><div class="spacegrid">${cards||'<div class="space">Aucun espace configuré.</div>'}</div>`)}
function brand(){return layout('Personnalisation','Identité de votre établissement.','',`<div class="card"><div class="field"><label>NOM AFFICHÉ</label><input value="${S.name}" disabled></div><p class="muted">La personnalisation sera enregistrée dans le compte établissement.</p></div>`)}
function billing(){const e=S.est||{},st=e.subscription_status||'trialing';let top=st==='trialing'?`<div class="notice ${active()?'success':''}"><b>Essai gratuit ${active()?'actif':'terminé'}</b><br>${days()} jour${days()>1?'s':''} restant${days()>1?'s':''} sur 14.</div>`:st==='active'?`<div class="notice success"><b>Abonnement actif · ${(e.plan_code||'FORMULE').toUpperCase()}</b><br>${e.current_period_end?'Prochaine échéance : '+new Date(e.current_period_end).toLocaleDateString('fr-FR'):'Accès actif'}</div>`:`<div class="notice"><b>Accès suspendu</b><br>Un abonnement actif est nécessaire pour lancer de nouvelles parties.</div>`;return layout('Abonnement','Statut lié au compte connecté.','',`${top}<div class="billingplans"><div class="plan"><b>STARTER</b><h3>29€<small>/mois</small></h3><button class="btn" data-plan="Starter">Choisir</button></div><div class="plan hot"><b>PRO</b><h3>59€<small>/mois</small></h3><button class="btn primary" data-plan="Pro">Choisir Pro</button></div><div class="plan"><b>PREMIUM</b><h3>99€<small>/mois</small></h3><button class="btn" data-plan="Premium">Choisir</button></div></div><div class="card" style="margin-top:10px"><b>Compte connecté</b><p class="muted">${S.user?.email||''} · rôle ${S.member?.role||''}</p></div>`)}
function render(){const f={home,new:newGame,questions,stats,spaces,brand,billing}[S.tab];$('#main').innerHTML=f();$$('#menu button').forEach(b=>b.classList.toggle('sel',b.dataset.tab===S.tab));bind()}
function bind(){$$('[data-tab]').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab==='new'&&!active()?'billing':b.dataset.tab;render()});$$('[data-filter]').forEach(b=>b.onclick=()=>{S.filter=b.dataset.filter;render()});$$('.choices button').forEach(b=>b.onclick=()=>{$$('.choices button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel')});$$('.cats button').forEach(b=>b.onclick=()=>b.classList.toggle('on'));const p=$('#prev'),n=$('#next');if(p)p.onclick=()=>{S.step=Math.max(1,S.step-1);render()};if(n)n.onclick=()=>{if(S.step<4){S.step++;render()}else openTv()};$$('.openTv').forEach(b=>b.onclick=openTv);const o=$('#openTv');if(o)o.onclick=openTv;$$('[data-plan]').forEach(b=>b.onclick=()=>alert('Paiement Stripe à brancher sur '+b.dataset.plan+'. Le statut d’abonnement affiché ici vient déjà de Supabase.'))}
let timer;function openTv(){if(!active()){S.tab='billing';render();show('app');return}show('tv');clearInterval(timer);let t=20;$('#timer').textContent=t;timer=setInterval(()=>{if(--t<=0){clearInterval(timer);const a=$$('#answers div');a[0].style.borderColor='#46d597';a.slice(1).forEach(x=>x.style.opacity=.35)}$('#timer').textContent=Math.max(t,0)},1000)}$('#back').onclick=()=>{render();show('app')};
(async()=>{try{const{data:{session}}=await supabase.auth.getSession();if(session)await loadAccount();else render()}catch(e){console.error(e);show('landing')}})();