import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm";
const sb=createClient("https://otgubsvmcbaocrndngrq.supabase.co","sb_publishable__d50uWZVhfLcfzHv70ZOSA_QySE92AW",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const Q={user:null,est:null,spaces:[],sessions:[],current:null,info:null,tvPoll:null,countTick:null,phaseTick:null,playerPoll:null,pendingSpace:null,pendingTitle:'Quiz',advanceBusy:false,lastTvKey:'',lastPlayerKey:''};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const letters=['A','B','C','D','E','F'];
function page(id){$$('.page').forEach(x=>x.classList.remove('on'));$('#'+id)?.classList.add('on');scrollTo(0,0)}
function urlPlayer(){return location.origin+location.pathname+'?play=1'}
function qr(id,size){const e=$(id);if(!e)return;e.innerHTML='';if(window.QRCode)new QRCode(e,{text:urlPlayer(),width:size,height:size,colorDark:'#08080c',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.M});else e.innerHTML='<div class="qrFallback">QR</div>'}
function secondsLeft(start,duration){return Math.max(0,Number(duration||0)-(start?(Date.now()-new Date(start).getTime())/1000:0))}
function remainIntro(i){return secondsLeft(i?.phase_started_at,i?.intro_duration||60)}
function fmt(n){n=Math.max(0,Math.ceil(n));return n>=60?`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`:String(n)}
async function snapshot(code,token=null){const{data,error}=await sb.rpc('nightquiz_game_snapshot',{p_code:String(code||''),p_player_token:token||null});if(error)throw error;return data||null}
async function leaderboard(code,limit=10){const{data,error}=await sb.rpc('nightquiz_leaderboard',{p_code:String(code||''),p_limit:limit});if(error)throw error;return Array.isArray(data)?data:[]}
async function ctx(){const{data:{user}}=await sb.auth.getUser();Q.user=user;if(!user)return;const{data:m}=await sb.from('nightquiz_memberships').select('establishment_id').eq('user_id',user.id).limit(1);if(!m?.[0])return;const id=m[0].establishment_id;const[a,b,c]=await Promise.all([sb.from('nightquiz_establishments').select('*').eq('id',id).single(),sb.from('nightquiz_spaces').select('*').eq('establishment_id',id).order('created_at'),sb.from('nightquiz_sessions').select('*').eq('establishment_id',id).in('status',['draft','lobby','running','paused']).order('created_at',{ascending:false})]);Q.est=a.data;Q.spaces=b.data||[];Q.sessions=c.data||[];Q.current=Q.current&&Q.sessions.find(x=>x.id===Q.current.id)||Q.sessions[0]||null;Q.info=Q.current?await snapshot(Q.current.game_code).catch(()=>null):null;patchCode()}
function patchCode(){const code=Q.current?.game_code;if(!code)return;const b=$('#main .code b');if(b){b.textContent=code;b.classList.add('nq-code-live')}const card=$('#main .code')?.parentElement;if(card&&!card.querySelector('.nq-newcode-note'))card.insertAdjacentHTML('beforeend','<div class="nq-newcode-note">Le code change automatiquement à chaque nouvelle partie.</div>')}
async function createGame(){await ctx();if(!Q.user)throw new Error('Connectez-vous d’abord.');let sp=Q.spaces.find(x=>x.name===Q.pendingSpace)||Q.spaces[0];if(!sp)throw new Error('Aucun espace disponible.');const{data,error}=await sb.rpc('nightquiz_create_session',{p_space_id:sp.id,p_title:Q.pendingTitle||'Quiz',p_question_count:30,p_question_duration:20,p_between_duration:5,p_intro_duration:60,p_categories:['MUSIQUE','CULTURE GÉNÉRALE','SPORT'],p_prize_first:null,p_prize_second:null,p_prize_third:null});if(error)throw error;await ctx();Q.current=Q.sessions.find(x=>x.id===data?.[0]?.session_id)||Q.sessions[0];Q.info=Q.current?await snapshot(Q.current.game_code):null;openTV()}
function clearTV(){clearInterval(Q.tvPoll);clearInterval(Q.countTick);clearInterval(Q.phaseTick);Q.tvPoll=Q.countTick=Q.phaseTick=null;Q.lastTvKey='';Q.advanceBusy=false}
function setStage(which){['#tvLobby','#tvCountdown','#tvQuestion'].forEach(x=>{const e=$(x);if(e)e.style.display='none'});const el=$(which);if(el)el.style.display=which==='#tvQuestion'?'block':'grid'}
function tvInfo(){if(!Q.info)return;$('#tvCodeLarge').textContent=Q.info.game_code||'----';$('#tvCodeMini').textContent=Q.info.game_code||'----';$('#tvPlayers').textContent=`${Q.info.player_count||0} joueur${Q.info.player_count===1?'':'s'}`;$('#tvVenue').textContent=Q.info.establishment_name||Q.est?.name||'NIGHTQUIZ';$('#tvSpace').textContent=Q.spaces.find(x=>x.id===Q.current?.space_id)?.name||'Espace principal'}
function tvKey(){return`${Q.info?.phase||''}:${Q.info?.question_number||0}:${Q.info?.phase_started_at||''}`}
function renderTV(force=false){if(!Q.current||!Q.info)return;tvInfo();const key=tvKey();if(!force&&key===Q.lastTvKey)return;Q.lastTvKey=key;clearInterval(Q.phaseTick);const p=Q.info.phase||'lobby';if(p==='lobby'){setStage('#tvLobby');$('#tvMiniJoin').style.display='none';qr('#tvQrLarge',240);$('#startQuiz').disabled=false;$('#startQuiz').textContent='▶ Lancer le quiz'}else if(p==='countdown'){setStage('#tvCountdown');$('#tvMiniJoin').style.display='flex';qr('#tvQrMini',82);tickCountdown()}else if(p==='question'){renderQuestionTV(false)}else if(p==='reveal'){renderQuestionTV(true)}else if(p==='leaderboard'){renderLeaderboardTV(false)}else if(p==='finished'){renderLeaderboardTV(true)}else{setStage('#tvQuestion');$('#tvQuestion').innerHTML='<div class="nqCenter"><h1>Partie en pause</h1></div>'}}
function tickCountdown(){clearInterval(Q.countTick);const tick=async()=>{const r=remainIntro(Q.info);$('#startCount').textContent=fmt(r);$('#startProgress').style.setProperty('--p',Math.max(0,Math.min(1,r/(Q.info?.intro_duration||60))));if(r<=0&&Q.user&&!Q.advanceBusy){clearInterval(Q.countTick);Q.advanceBusy=true;const{error}=await sb.rpc('nightquiz_mark_running',{p_session_id:Q.current.id});Q.advanceBusy=false;if(!error){Q.info=await snapshot(Q.current.game_code);renderTV(true)}}};tick();Q.countTick=setInterval(tick,250)}
function renderQuestionTV(reveal){setStage('#tvQuestion');$('#tvMiniJoin').style.display='flex';qr('#tvQrMini',82);const q=Q.info.question;if(!q){$('#tvQuestion').innerHTML='<div class="nqCenter"><h1>Chargement de la question…</h1></div>';return}const correct=new Set(Array.isArray(Q.info.correct_indices)?Q.info.correct_indices:[]);$('#tvQuestion').innerHTML=`<div class="nqQuestionMeta"><span>${esc(q.category||'QUIZ')} · QUESTION ${Q.info.question_number||1} / ${Q.info.total_questions||0}</span><span>${reveal?'RÉPONSE':'À VOUS DE JOUER'}</span></div><h1>${esc(q.text)}</h1><div class="answers nqTvAnswers">${(q.answers||[]).map((a,i)=>`<div class="${reveal?(correct.has(i)?'nqCorrect':'nqDim'):''}"><b>${letters[i]||i+1}</b> ${esc(a)}</div>`).join('')}</div><div class="nqTimerRow"><div class="timer" id="timer">${reveal?'✓':Q.info.question_duration}</div><div class="nqQuestionStatus" id="nqQuestionStatus">${reveal?'Bonne réponse affichée':'Répondez depuis votre téléphone'}</div></div>`;if(reveal)tickBetween();else tickQuestion()}
function tickQuestion(){clearInterval(Q.phaseTick);const tick=async()=>{const r=secondsLeft(Q.info.question_started_at,Q.info.question_duration);const t=$('#timer');if(t)t.textContent=fmt(r);if(r<=0&&Q.user&&!Q.advanceBusy){clearInterval(Q.phaseTick);await advanceGame()}};tick();Q.phaseTick=setInterval(tick,200)}
function tickBetween(){clearInterval(Q.phaseTick);const duration=Math.max(2,Q.info.between_question_duration||5);const status=$('#nqQuestionStatus');const tick=async()=>{const r=secondsLeft(Q.info.phase_started_at,duration);if(status)status.textContent=`Question suivante dans ${fmt(r)}`;if(r<=0&&Q.user&&!Q.advanceBusy){clearInterval(Q.phaseTick);await advanceGame()}};tick();Q.phaseTick=setInterval(tick,250)}
async function renderLeaderboardTV(final=false){setStage('#tvQuestion');$('#tvMiniJoin').style.display=final?'none':'flex';if(!final)qr('#tvQrMini',82);const rows=await leaderboard(Q.info.game_code,10).catch(()=>[]);$('#tvQuestion').innerHTML=`<div class="nqCenter nqBoard"><span class="pill">${final?'CLASSEMENT FINAL':'CLASSEMENT'}</span><h1>${final?'🏆 Résultats du quiz':'Top joueurs'}</h1><div class="nqLeaderboard">${rows.length?rows.map(r=>`<div class="nqRank ${r.rank<=3?'top':''}"><strong>${r.rank===1?'🥇':r.rank===2?'🥈':r.rank===3?'🥉':'#'+r.rank}</strong><span>${esc(r.nickname)}</span><b>${r.score} pts</b></div>`).join(''):'<p>Aucun joueur.</p>'}</div>${final?'<p class="nqFinalMsg">Merci d’avoir joué !</p>':'<p id="nqBoardNext">Prochaine question dans quelques secondes…</p>'}</div>`;if(!final){clearInterval(Q.phaseTick);const duration=Math.max(5,Q.info.between_question_duration||5);const tick=async()=>{const r=secondsLeft(Q.info.phase_started_at,duration);const x=$('#nqBoardNext');if(x)x.textContent=`Prochaine question dans ${fmt(r)}`;if(r<=0&&Q.user&&!Q.advanceBusy){clearInterval(Q.phaseTick);await advanceGame()}};tick();Q.phaseTick=setInterval(tick,250)}}
async function advanceGame(){if(!Q.current||Q.advanceBusy)return;Q.advanceBusy=true;try{const{data,error}=await sb.rpc('nightquiz_advance_game',{p_session_id:Q.current.id});if(error)throw error;Q.info=data||await snapshot(Q.current.game_code);Q.lastTvKey='';renderTV(true)}catch(e){console.error(e)}finally{Q.advanceBusy=false}}
async function refreshTV(){if(!Q.current)return;const n=await snapshot(Q.current.game_code).catch(()=>null);if(!n)return;Q.info=n;tvInfo();renderTV()}
async function openTV(){if(!Q.current){alert('Créez d’abord une nouvelle partie.');return}clearTV();Q.info=await snapshot(Q.current.game_code).catch(()=>null);if(!Q.info){alert('Cette partie n’est plus active.');return}page('tv');renderTV(true);Q.tvPoll=setInterval(refreshTV,1000)}
async function launch(){const b=$('#startQuiz');b.disabled=true;b.textContent='Lancement…';const{error}=await sb.rpc('nightquiz_start_countdown',{p_session_id:Q.current.id});if(error){b.disabled=false;b.textContent='▶ Lancer le quiz';alert(error.message);return}Q.info=await snapshot(Q.current.game_code);Q.lastTvKey='';renderTV(true)}
function playerBase(i){$('#playerGameCode').textContent=i.game_code||'----';$('#playerVenue').textContent=i.establishment_name||'NIGHTQUIZ'}
function playerWaiting(title,text,count=null){const box=$('#playerState');box.innerHTML=`<div class="playerStatusIcon">✓</div><h2>${esc(title)}</h2><p>${esc(text)}</p>${count!==null?`<div class="playerCountdown">${fmt(count)}</div>`:''}`}
function playerQuestion(i,p){const q=i.question,answered=!!p?.answered,remaining=secondsLeft(i.question_started_at,i.question_duration);const box=$('#playerState');box.innerHTML=`<div class="nqPlayerMeta"><span>QUESTION ${i.question_number} / ${i.total_questions}</span><b>${p?.score||0} pts · #${p?.rank||'—'}</b></div><h2 class="nqPlayerQuestion">${esc(q?.text||'Question')}</h2><div class="nqPlayerAnswers">${(q?.answers||[]).map((a,idx)=>`<button data-answer="${idx}" ${answered||remaining<=0?'disabled':''}><b>${letters[idx]||idx+1}</b><span>${esc(a)}</span></button>`).join('')}</div><div class="nqPlayerTimer"><strong id="playerQuestionTimer">${fmt(remaining)}</strong><span>${answered?'Réponse enregistrée ✓':'Choisis ta réponse'}</span></div>`;if(!answered&&remaining>0)$$('[data-answer]').forEach(b=>b.onclick=()=>submitAnswer(Number(b.dataset.answer)));tickPlayerQuestion(i)}
function tickPlayerQuestion(i){clearInterval(Q.phaseTick);const tick=()=>{const t=$('#playerQuestionTimer');if(!t)return;const r=secondsLeft(i.question_started_at,i.question_duration);t.textContent=fmt(r);if(r<=0){$$('[data-answer]').forEach(b=>b.disabled=true);clearInterval(Q.phaseTick)}};tick();Q.phaseTick=setInterval(tick,200)}
async function submitAnswer(index){const raw=localStorage.getItem('nightquiz_player');if(!raw)return;let p;try{p=JSON.parse(raw)}catch{return}$$('[data-answer]').forEach(b=>b.disabled=true);const status=$('.nqPlayerTimer span');if(status)status.textContent='Envoi de la réponse…';try{const{error}=await sb.rpc('nightquiz_submit_answer',{p_code:p.game_code,p_player_token:p.player_token,p_answer_index:index});if(error)throw error;if(status)status.textContent='Réponse enregistrée ✓';const i=await snapshot(p.game_code,p.player_token);if(i)joinState(i,p,true)}catch(e){if(status)status.textContent=e.message||'Réponse impossible'}}
function playerReveal(i,p){const correct=p?.answer_correct===true,answered=p?.answered===true;const pts=p?.points_awarded||0;const good=Array.isArray(i.correct_indices)?new Set(i.correct_indices):new Set();const q=i.question;$('#playerState').innerHTML=`<div class="playerStatusIcon ${correct?'':'nqWrong'}">${correct?'✓':answered?'×':'…'}</div><h2>${correct?'Bonne réponse !':answered?'Mauvaise réponse':'Temps écoulé'}</h2><p>${correct?`+${pts} points`:'La bonne réponse est affichée sur la TV.'}</p><div class="nqRevealAnswers">${(q?.answers||[]).map((a,idx)=>`<div class="${good.has(idx)?'nqCorrect':''}"><b>${letters[idx]||idx+1}</b> ${esc(a)}</div>`).join('')}</div><div class="nqPlayerScore">Score : <b>${p?.score||0} pts</b> · Rang <b>#${p?.rank||'—'}</b></div>`}
async function playerBoard(i,p,final=false){const rows=await leaderboard(i.game_code,5).catch(()=>[]);$('#playerState').innerHTML=`<span class="pill">${final?'RÉSULTATS':'CLASSEMENT'}</span><h2>${final?'Quiz terminé 🏆':'Top 5'}</h2><div class="nqLeaderboard nqLeaderboardPhone">${rows.map(r=>`<div class="nqRank ${r.rank<=3?'top':''}"><strong>#${r.rank}</strong><span>${esc(r.nickname)}</span><b>${r.score}</b></div>`).join('')}</div><div class="nqPlayerScore">Ton score : <b>${p?.score||0} pts</b> · Rang <b>#${p?.rank||'—'}</b></div>`}
async function joinState(i,stored,force=false){if(!i){playerWaiting('Partie terminée','Cette partie n’est plus disponible.');return}playerBase(i);const p=i.player||{};const key=`${i.phase}:${i.question_number||0}:${p.answered||false}:${p.score||0}:${p.answer_correct}:${i.phase_started_at||''}`;if(!force&&key===Q.lastPlayerKey){if(i.phase==='countdown'){$('.playerCountdown').textContent=fmt(remainIntro(i))}return}Q.lastPlayerKey=key;clearInterval(Q.phaseTick);if(i.phase==='lobby')playerWaiting('Tu es inscrit ✓','Pas besoin de validation staff. Attends le lancement du quiz.');else if(i.phase==='countdown')playerWaiting('Prépare-toi !','Le quiz va commencer.',remainIntro(i));else if(i.phase==='question')playerQuestion(i,p);else if(i.phase==='reveal')playerReveal(i,p);else if(i.phase==='leaderboard')await playerBoard(i,p,false);else if(i.phase==='finished')await playerBoard(i,p,true);else playerWaiting('Partie en pause','La partie reprendra bientôt.')}
function playerWatch(p){clearInterval(Q.playerPoll);const t=async()=>{const i=await snapshot(p.game_code,p.player_token).catch(()=>null);await joinState(i,p)};t();Q.playerPoll=setInterval(t,800)}
async function playerInit(){page('player');$('#playerJoinBox').style.display='block';$('#playerJoinedBox').style.display='none';const raw=localStorage.getItem('nightquiz_player');if(raw)try{const p=JSON.parse(raw),i=await snapshot(p.game_code,p.player_token);if(i&&i.player){$('#playerJoinBox').style.display='none';$('#playerJoinedBox').style.display='block';$('#playerNick').textContent=p.nickname;playerWatch(p)}else localStorage.removeItem('nightquiz_player')}catch{localStorage.removeItem('nightquiz_player')}}
$('#playerJoinForm')?.addEventListener('submit',async e=>{e.preventDefault();const code=$('#joinCode').value.replace(/\D/g,'').slice(0,4),nick=$('#joinPseudo').value.trim(),er=$('#joinError'),bt=$('#joinSubmit');er.style.display='none';if(code.length!==4||!nick){er.textContent='Entre le code à 4 chiffres et ton pseudo.';er.style.display='block';return}bt.disabled=true;try{const{data,error}=await sb.rpc('nightquiz_join_game',{p_code:code,p_nickname:nick});if(error)throw error;const p={...data[0],nickname:nick};localStorage.setItem('nightquiz_player',JSON.stringify(p));$('#playerJoinBox').style.display='none';$('#playerJoinedBox').style.display='block';$('#playerNick').textContent=nick;$('#playerVenue').textContent=p.establishment_name;Q.lastPlayerKey='';playerWatch(p)}catch(x){er.textContent=(x.message||'Impossible de rejoindre.').replace(/^.*?: /,'');er.style.display='block'}finally{bt.disabled=false}});
$('#joinCode')?.addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,4));$('#changePlayer')?.addEventListener('click',()=>{clearInterval(Q.playerPoll);clearInterval(Q.phaseTick);localStorage.removeItem('nightquiz_player');Q.lastPlayerKey='';$('#playerJoinedBox').style.display='none';$('#playerJoinBox').style.display='block'});$('#startQuiz')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();launch()});$('#tvBack')?.addEventListener('click',e=>{e.preventDefault();clearTV();page('app')});
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;if(t.id==='next'){const sel=$('#main select');if(sel){const inp=$('#main input');if(inp)Q.pendingTitle=inp.value;Q.pendingSpace=sel.options?.[sel.selectedIndex]?.text}if(/créer/i.test(t.textContent)){e.preventDefault();e.stopImmediatePropagation();t.disabled=true;t.textContent='Création…';try{await createGame()}catch(x){alert(x.message);t.disabled=false;t.textContent='Créer et ouvrir la TV'}return}}if(t.id==='openTv'||t.classList.contains('openTv')){e.preventDefault();e.stopImmediatePropagation();await ctx();openTV()}},true);
new MutationObserver(()=>patchCode()).observe($('#main'),{childList:true,subtree:true});sb.auth.onAuthStateChange(()=>setTimeout(ctx,0));
(async()=>{if(new URLSearchParams(location.search).get('play')==='1'){await playerInit();return}await ctx()})();