import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm";
const sb=createClient("https://otgubsvmcbaocrndngrq.supabase.co","sb_publishable__d50uWZVhfLcfzHv70ZOSA_QySE92AW",{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const Q={user:null,est:null,spaces:[],sessions:[],current:null,info:null,tvPoll:null,countTick:null,playerPoll:null,pendingSpace:null,pendingTitle:'Quiz'};
function page(id){$$('.page').forEach(x=>x.classList.remove('on'));$('#'+id)?.classList.add('on');scrollTo(0,0)}
function urlPlayer(){return location.origin+location.pathname+'?play=1'}
function qr(id,size){const e=$(id);if(!e)return;e.innerHTML='';if(window.QRCode)new QRCode(e,{text:urlPlayer(),width:size,height:size,colorDark:'#08080c',colorLight:'#fff',correctLevel:QRCode.CorrectLevel.M});else e.innerHTML='<div class="qrFallback">QR</div>'}
function remain(i){return Math.max(0,(i?.intro_duration||60)-(i?.phase_started_at?(Date.now()-new Date(i.phase_started_at).getTime())/1000:0))}
function fmt(n){n=Math.max(0,Math.ceil(n));return n>=60?`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`:String(n)}
async function pub(code){const{data,error}=await sb.rpc('nightquiz_public_session',{p_code:String(code||'')});if(error)throw error;return data?.[0]||null}
async function ctx(){const{data:{user}}=await sb.auth.getUser();Q.user=user;if(!user)return;const{data:m}=await sb.from('nightquiz_memberships').select('establishment_id').eq('user_id',user.id).limit(1);if(!m?.[0])return;const id=m[0].establishment_id;const[a,b,c]=await Promise.all([sb.from('nightquiz_establishments').select('*').eq('id',id).single(),sb.from('nightquiz_spaces').select('*').eq('establishment_id',id).order('created_at'),sb.from('nightquiz_sessions').select('*').eq('establishment_id',id).in('status',['draft','lobby','running','paused']).order('created_at',{ascending:false})]);Q.est=a.data;Q.spaces=b.data||[];Q.sessions=c.data||[];Q.current=Q.current&&Q.sessions.find(x=>x.id===Q.current.id)||Q.sessions[0]||null;Q.info=Q.current?await pub(Q.current.game_code).catch(()=>null):null;patchCode()}
function patchCode(){const code=Q.current?.game_code;if(!code)return;const b=$('#main .code b');if(b){b.textContent=code;b.classList.add('nq-code-live')}const card=$('#main .code')?.parentElement;if(card&&!card.querySelector('.nq-newcode-note'))card.insertAdjacentHTML('beforeend','<div class="nq-newcode-note">Le code change automatiquement à chaque nouvelle partie.</div>')}
async function createGame(){await ctx();if(!Q.user)throw new Error('Connectez-vous d’abord.');let sp=Q.spaces.find(x=>x.name===Q.pendingSpace)||Q.spaces[0];if(!sp)throw new Error('Aucun espace disponible.');const{data,error}=await sb.rpc('nightquiz_create_session',{p_space_id:sp.id,p_title:Q.pendingTitle||'Quiz',p_question_count:30,p_question_duration:20,p_between_duration:5,p_intro_duration:60,p_categories:['Musique','Culture générale','Sport'],p_prize_first:null,p_prize_second:null,p_prize_third:null});if(error)throw error;await ctx();Q.current=Q.sessions.find(x=>x.id===data?.[0]?.session_id)||Q.sessions[0];Q.info=Q.current?await pub(Q.current.game_code):null;openTV()}
function clearTV(){clearInterval(Q.tvPoll);clearInterval(Q.countTick);Q.tvPoll=Q.countTick=null}
function setStage(which){['#tvLobby','#tvCountdown','#tvQuestion'].forEach(x=>{const e=$(x);if(e)e.style.display='none'});$(which).style.display=which==='#tvQuestion'?'block':'grid'}
function tvInfo(){if(!Q.info)return;$('#tvCodeLarge').textContent=Q.info.game_code;$('#tvCodeMini').textContent=Q.info.game_code;$('#tvPlayers').textContent=`${Q.info.player_count||0} joueur${Q.info.player_count===1?'':'s'}`;$('#tvVenue').textContent=Q.info.establishment_name||Q.est?.name||'NIGHTQUIZ';$('#tvSpace').textContent=Q.spaces.find(x=>x.id===Q.current?.space_id)?.name||'Espace principal'}
function renderTV(){if(!Q.current||!Q.info)return;tvInfo();const p=Q.info.phase||'lobby';if(p==='lobby'){setStage('#tvLobby');$('#tvMiniJoin').style.display='none';qr('#tvQrLarge',240);$('#startQuiz').disabled=false;$('#startQuiz').textContent='▶ Lancer le quiz'}else if(p==='countdown'){setStage('#tvCountdown');$('#tvMiniJoin').style.display='flex';qr('#tvQrMini',82);tickCountdown()}else{setStage('#tvQuestion');$('#tvMiniJoin').style.display='flex';qr('#tvQrMini',82)}}
function tickCountdown(){clearInterval(Q.countTick);const tick=async()=>{const r=remain(Q.info);$('#startCount').textContent=fmt(r);$('#startProgress').style.setProperty('--p',Math.max(0,Math.min(1,r/(Q.info?.intro_duration||60))));if(r<=0&&Q.user){clearInterval(Q.countTick);const{error}=await sb.rpc('nightquiz_mark_running',{p_session_id:Q.current.id});if(!error){Q.info=await pub(Q.current.game_code);renderTV()}}};tick();Q.countTick=setInterval(tick,250)}
async function refreshTV(){if(!Q.current)return;const n=await pub(Q.current.game_code).catch(()=>null);if(!n)return;const changed=n.phase!==Q.info?.phase;Q.info=n;tvInfo();if(changed)renderTV()}
async function openTV(){if(!Q.current){alert('Créez d’abord une nouvelle partie.');return}clearTV();Q.info=await pub(Q.current.game_code).catch(()=>null);if(!Q.info){alert('Cette partie n’est plus active.');return}page('tv');renderTV();Q.tvPoll=setInterval(refreshTV,1200)}
async function launch(){const b=$('#startQuiz');b.disabled=true;b.textContent='Lancement…';const{error}=await sb.rpc('nightquiz_start_countdown',{p_session_id:Q.current.id});if(error){b.disabled=false;b.textContent='▶ Lancer le quiz';alert(error.message);return}Q.info=await pub(Q.current.game_code);renderTV()}
function joinState(i){if(!i){$('#playerStateTitle').textContent='Partie terminée';$('#playerStateText').textContent='Cette partie n’est plus disponible.';$('#playerCountdown').style.display='none';return}$('#playerGameCode').textContent=i.game_code;$('#playerVenue').textContent=i.establishment_name||'NIGHTQUIZ';if(i.phase==='lobby'){$('#playerStateTitle').textContent='Tu es inscrit ✓';$('#playerStateText').textContent='Pas besoin de validation staff. Attends le lancement du quiz.';$('#playerCountdown').style.display='none'}else if(i.phase==='countdown'){$('#playerStateTitle').textContent='Prépare-toi !';$('#playerStateText').textContent='Le quiz va commencer.';$('#playerCountdown').style.display='block';$('#playerCountdown').textContent=fmt(remain(i))}else{$('#playerStateTitle').textContent='C’est parti !';$('#playerStateText').textContent='Regarde la TV : les réponses apparaîtront ici pendant le quiz.';$('#playerCountdown').style.display='none'}}
function playerWatch(p){clearInterval(Q.playerPoll);const t=async()=>joinState(await pub(p.game_code).catch(()=>null));t();Q.playerPoll=setInterval(t,1000)}
async function playerInit(){page('player');$('#playerJoinBox').style.display='block';$('#playerJoinedBox').style.display='none';const raw=localStorage.getItem('nightquiz_player');if(raw)try{const p=JSON.parse(raw),i=await pub(p.game_code);if(i){$('#playerJoinBox').style.display='none';$('#playerJoinedBox').style.display='block';$('#playerNick').textContent=p.nickname;playerWatch(p)}}catch{} }
$('#playerJoinForm')?.addEventListener('submit',async e=>{e.preventDefault();const code=$('#joinCode').value.replace(/\D/g,'').slice(0,4),nick=$('#joinPseudo').value.trim(),er=$('#joinError'),bt=$('#joinSubmit');er.style.display='none';if(code.length!==4||!nick){er.textContent='Entre le code à 4 chiffres et ton pseudo.';er.style.display='block';return}bt.disabled=true;try{const{data,error}=await sb.rpc('nightquiz_join_game',{p_code:code,p_nickname:nick});if(error)throw error;const p={...data[0],nickname:nick};localStorage.setItem('nightquiz_player',JSON.stringify(p));$('#playerJoinBox').style.display='none';$('#playerJoinedBox').style.display='block';$('#playerNick').textContent=nick;$('#playerVenue').textContent=p.establishment_name;playerWatch(p)}catch(x){er.textContent=(x.message||'Impossible de rejoindre.').replace(/^.*?: /,'');er.style.display='block'}finally{bt.disabled=false}});
$('#joinCode')?.addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,4));$('#changePlayer')?.addEventListener('click',()=>{clearInterval(Q.playerPoll);localStorage.removeItem('nightquiz_player');$('#playerJoinedBox').style.display='none';$('#playerJoinBox').style.display='block'});$('#startQuiz')?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();launch()});$('#tvBack')?.addEventListener('click',e=>{e.preventDefault();clearTV();page('app')});
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;if(t.id==='next'){const inp=$('#main input'),sel=$('#main select');if(inp)Q.pendingTitle=inp.value;if(sel)Q.pendingSpace=sel.options?.[sel.selectedIndex]?.text;if(/créer/i.test(t.textContent)){e.preventDefault();e.stopImmediatePropagation();t.disabled=true;t.textContent='Création…';try{await createGame()}catch(x){alert(x.message);t.disabled=false;t.textContent='Créer et ouvrir la TV'}return}}if(t.id==='openTv'||t.classList.contains('openTv')){e.preventDefault();e.stopImmediatePropagation();await ctx();openTV()}},true);
new MutationObserver(()=>patchCode()).observe($('#main'),{childList:true,subtree:true});sb.auth.onAuthStateChange(()=>setTimeout(ctx,0));
(async()=>{if(new URLSearchParams(location.search).get('play')==='1'){await playerInit();return}await ctx()})();